baseURL = 'https://gm-test-learn-hugo.s3-website.us-east-2.amazonaws.com/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'PaperMod'

#TODO - see how we can dynamically pull in s3 bucket names
[deployment]
  [[deployment.targets]]
    name = 'dev'
    url = 's3://gm-test-learn-hugo/?region=us-east-2'
  [[deployment.targets]]
    name = 'prod'
    url = 's3://gm-test-learn-hugo/?region=us-east-2'

# Enable main menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/page/projects/"
    weight = 3
  [[menu.main]]
    identifier = "render-hooks"
    name = "Render Hooks"
    url = "/page/render-hooks/"
    weight = 3.5
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/page/contact/"
    weight = 5

# Theme parameters
[params]
  # Show navigation bar
  defaultTheme = "auto"
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowShareButtons = true
