baseURL = 'https://learn-hugo.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'PaperMod'

[deployment]
  [[deployment.targets]]
    name = 'dev'
    url = 's3://gm-dev-hugo-learn-td76c/?region=us-east-1'

# Enable main menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/page/projects/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/page/contact/"
    weight = 5

# Theme parameters
[params]
  # Show navigation bar
  defaultTheme = "auto"
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowShareButtons = true
